displayName=Better Bank
author=Aiden Wesley
description=Group your bank by category and switch between organising schemes
tags=bank,category,categories,organise,organize,sort,scheme,tags
plugins=com.betterbank.BetterBankPlugin
version=1.0.0
build=standard
