displayName=Better Bank
author=Aiden Wesley
description=Automatically categorises your bank and groups it by category
tags=bank,category,categories,sort,organise,organize
version=0.0.1
plugins=com.betterbank.BetterBankPlugin
build=standard
